import tseslint from 'typescript-eslint'
import boundaries from 'eslint-plugin-boundaries'

// FE-019 — Import-boundary enforcement (eslint-plugin-boundaries v6).
//
// Layering (each layer may only depend on the ones to its right):
//   routes  →  features (own feature only)  →  shared  →  shared
//
// A single `boundaries/dependencies` rule (the v6 successor to the legacy
// element-types + entry-point rules) encodes both concerns at `error` level:
//   1. DIRECTION — no feature→feature (cross-feature) imports and no
//      shared→feature imports; routes/app may reach features + shared.
//   2. BARREL-ONLY — code OUTSIDE a feature may only import `@/features/<x>`
//      (its index.ts public API), never a deep path like `@/features/<x>/api`.
//      This is enforced via the `to.internalPath: 'index.ts'` selector.
//      Intra-feature imports are "internal" (same element) and exempt, so
//      `src/features/sessions/components/timeline.tsx` may freely import
//      `@/features/sessions/api` / `useSessions`.
//
// FE-023 (NICE) can extend the `rules` block below with a naming/derive
// guardrail (e.g. a no-restricted-syntax or custom rule) without touching the
// element/boundary wiring.

export default tseslint.config(
  // Generated + non-source: never lint.
  {
    ignores: [
      'dist/**',
      'node_modules/**',
      'src/routeTree.gen.ts', // generated by @tanstack/router-plugin
    ],
  },

  // Boundary enforcement. Tight by design: the GOAL of FE-019 is the import
  // boundary, not a style ruleset. We deliberately do NOT pull in
  // js/tseslint `recommended` here — those surface pre-existing style issues
  // (unused vars, no-explicit-any in tests, etc.) that are out of scope and
  // would force source churn. The TS parser is still registered so .ts/.tsx
  // files parse correctly for the boundary analysis.
  {
    files: ['src/**/*.{ts,tsx}'],
    languageOptions: {
      parser: tseslint.parser,
      parserOptions: { ecmaFeatures: { jsx: true } },
    },
    // `@typescript-eslint` is registered (no rules enabled) so existing inline
    // `// eslint-disable-next-line @typescript-eslint/...` directives in source
    // resolve. We intentionally do NOT turn its rules on (out of scope).
    // Pre-existing disable directives target rules we don't enable, so don't
    // report them as "unused".
    linterOptions: { reportUnusedDisableDirectives: 'off' },
    plugins: { boundaries, '@typescript-eslint': tseslint.plugin },
    settings: {
      // `@` alias mirrors tsconfig `paths` so boundaries resolves it.
      'import/resolver': {
        typescript: { alwaysTryTypes: true },
      },
      'boundaries/include': ['src/**/*'],
      'boundaries/elements': [
        // Order matters: most-specific first.
        {
          type: 'feature',
          pattern: 'src/features/*',
          mode: 'folder',
          capture: ['feature'],
        },
        { type: 'shared', pattern: 'src/shared/*', mode: 'folder' },
        { type: 'routes', pattern: 'src/routes', mode: 'folder' },
        // App shell: main.tsx, router.tsx, etc. (top-level src files).
        { type: 'app', pattern: 'src/*', mode: 'file' },
      ],
    },
    rules: {
      'boundaries/dependencies': [
        'error',
        {
          // Disallow every cross-element dependency unless explicitly allowed.
          default: 'disallow',
          rules: [
            // Always allow internal imports (a file importing another file of
            // the SAME element instance) — this exempts intra-feature deep
            // imports such as timeline.tsx → sessions/api.
            { allow: { dependency: { relationship: { to: 'internal' } } } },

            // App shell (main.tsx, router.tsx, ...) wires the app: it may reach
            // routes, shared, and feature barrels.
            {
              from: { type: 'app' },
              allow: {
                to: [
                  { type: 'app' }, // e.g. main.tsx → ./router
                  { type: 'routes' },
                  { type: 'shared' },
                  { type: 'feature', internalPath: 'index.ts' },
                ],
              },
            },

            // Routes → shared, and feature BARRELS only.
            {
              from: { type: 'routes' },
              allow: {
                to: [
                  { type: 'shared' },
                  { type: 'feature', internalPath: 'index.ts' },
                ],
              },
            },

            // A feature → shared, and OTHER feature BARRELS only.
            // (Cross-feature is barrel-only; same-feature deep imports are
            // already covered by the `internal` rule above.)
            {
              from: { type: 'feature' },
              allow: {
                to: [
                  { type: 'shared' },
                  {
                    type: 'feature',
                    captured: { feature: '!{{ from.captured.feature }}' },
                    internalPath: 'index.ts',
                  },
                ],
              },
            },

            // Shared → shared ONLY. (No allowance to reach `feature`, so any
            // shared→feature import is disallowed by default.)
            { from: { type: 'shared' }, allow: { to: { type: 'shared' } } },
          ],
        },
      ],
    },
  },

  // Carve-out: test files may reach into feature internals (e.g.
  // src/routes/admin.gate.test.tsx imports `@/features/auth/api`).
  {
    files: ['**/*.test.{ts,tsx}'],
    rules: {
      'boundaries/dependencies': 'off',
    },
  },
)
