using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace JournalRecall.AI.SourceGeneration;

/// <summary>
/// Emits, with zero reflection (ADR-0004):
/// <list type="bullet">
/// <item>an <c>IAgentCatalog</c> registering every <c>IAgent</c> (built by calling its static <c>Configure</c>), plus <c>AddGeneratedAgents()</c>;</item>
/// <item>an <c>AddGeneratedTools()</c> extension registering every <c>ITool</c> in DI — an alternative to hand-written <c>AddTool&lt;T&gt;()</c>.</item>
/// </list>
/// </summary>
[Generator(Microsoft.CodeAnalysis.LanguageNames.CSharp)]
public sealed class AgentCatalogGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var discovered = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is ClassDeclarationSyntax { BaseList: not null },
                transform: static (ctx, _) => Classify(ctx))
            .Where(static d => d.IsAgent || d.IsTool)
            .Collect();

        context.RegisterSourceOutput(discovered, static (spc, items) => Emit(spc, items));
    }

    private static (string FullName, bool IsAgent, bool IsTool) Classify(GeneratorSyntaxContext ctx)
    {
        if (ctx.SemanticModel.GetDeclaredSymbol(ctx.Node) is not INamedTypeSymbol symbol)
            return (string.Empty, false, false);
        if (symbol.IsAbstract || symbol.TypeKind != TypeKind.Class)
            return (string.Empty, false, false);

        var interfaces = symbol.AllInterfaces.Select(i => i.ToDisplayString()).ToImmutableHashSet();
        var isAgent = interfaces.Contains(AgentContract.AgentInterface);
        var isTool = interfaces.Contains(AgentContract.ToolInterface);
        if (!isAgent && !isTool)
            return (string.Empty, false, false);

        return (symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat), isAgent, isTool);
    }

    private static void Emit(SourceProductionContext spc, ImmutableArray<(string FullName, bool IsAgent, bool IsTool)> items)
    {
        var agents = items.Where(i => i.IsAgent).Select(i => i.FullName).Distinct().OrderBy(n => n, System.StringComparer.Ordinal).ToList();
        var tools = items.Where(i => i.IsTool).Select(i => i.FullName).Distinct().OrderBy(n => n, System.StringComparer.Ordinal).ToList();

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine($"namespace {AgentContract.GeneratedNamespace}");
        sb.AppendLine("{");

        EmitCatalog(sb, agents);
        sb.AppendLine();
        EmitToolRegistration(sb, tools);

        sb.AppendLine("}");
        spc.AddSource("JournalRecallGenerated.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static void EmitCatalog(StringBuilder sb, System.Collections.Generic.List<string> agents)
    {
        sb.AppendLine("    internal sealed class GeneratedAgentCatalog : global::JournalRecall.AI.Core.IAgentCatalog");
        sb.AppendLine("    {");
        sb.AppendLine("        private readonly global::System.Collections.Generic.Dictionary<string, global::JournalRecall.AI.Core.AgentDefinition> _byName =");
        sb.AppendLine("            new global::System.Collections.Generic.Dictionary<string, global::JournalRecall.AI.Core.AgentDefinition>(global::System.StringComparer.Ordinal);");
        sb.AppendLine();
        sb.AppendLine("        public GeneratedAgentCatalog()");
        sb.AppendLine("        {");
        for (var i = 0; i < agents.Count; i++)
            sb.AppendLine($"            Add(Build_{i}());");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        private void Add(global::JournalRecall.AI.Core.AgentDefinition definition) => _byName[definition.Name] = definition;");
        sb.AppendLine();
        for (var i = 0; i < agents.Count; i++)
        {
            sb.AppendLine($"        private static global::JournalRecall.AI.Core.AgentDefinition Build_{i}()");
            sb.AppendLine("        {");
            sb.AppendLine($"            var builder = global::JournalRecall.AI.Core.Agent.Define({agents[i]}.Name);");
            sb.AppendLine($"            {agents[i]}.Configure(builder);");
            sb.AppendLine("            return builder.Build();");
            sb.AppendLine("        }");
            sb.AppendLine();
        }
        sb.AppendLine("        public global::System.Collections.Generic.IReadOnlyCollection<string> Names => _byName.Keys;");
        sb.AppendLine();
        sb.AppendLine("        public global::JournalRecall.AI.Core.AgentDefinition? Find(string name) =>");
        sb.AppendLine("            _byName.TryGetValue(name, out var definition) ? definition : null;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Registers the source-generated agent catalog.</summary>");
        sb.AppendLine("    public static class GeneratedAgentCatalogExtensions");
        sb.AppendLine("    {");
        sb.AppendLine("        public static global::JournalRecall.AI.DependencyInjection.IJournalRecallAgentsBuilder AddGeneratedAgents(");
        sb.AppendLine("            this global::JournalRecall.AI.DependencyInjection.IJournalRecallAgentsBuilder builder)");
        sb.AppendLine("        {");
        sb.AppendLine("            global::Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions.AddSingleton<global::JournalRecall.AI.Core.IAgentCatalog>(");
        sb.AppendLine("                builder.Services, new GeneratedAgentCatalog());");
        sb.AppendLine("            return builder;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
    }

    private static void EmitToolRegistration(StringBuilder sb, System.Collections.Generic.List<string> tools)
    {
        sb.AppendLine("    /// <summary>Registers all source-discovered ITool implementations (an alternative to AddTool&lt;T&gt;()).</summary>");
        sb.AppendLine("    public static class GeneratedToolExtensions");
        sb.AppendLine("    {");
        sb.AppendLine("        public static global::JournalRecall.AI.DependencyInjection.IJournalRecallAgentsBuilder AddGeneratedTools(");
        sb.AppendLine("            this global::JournalRecall.AI.DependencyInjection.IJournalRecallAgentsBuilder builder)");
        sb.AppendLine("        {");
        foreach (var tool in tools)
            sb.AppendLine($"            global::Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions.AddScoped<{tool}>(builder.Services);");
        sb.AppendLine("            return builder;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
    }
}
